### ISSUE TITLE
Translate plugin to brazilian portuguese

### ISSUE THREAD

**Issue by ChrystianDeMatos** [PauMAVA/UhcPlugin#11]
Translate to locale PT-br.
[lang_br.zip](https://github.com/PauMAVA/UhcPlugin/files/4226466/lang_br.zip)

**Comment by PauMAVA** [comment]
Hello!

Thank you so much for translating the plugin. I will add you translation in the following commit.

Thanks :)

**Comment by PauMAVA** [comment]
Added PT-br locale support on fd391fe

To use this locale use language code 'br' on the config file.

**Comment by ChrystianDeMatos** [comment]
no problem!
is there any way that i can test it? like, do i need to update the plugin or anything like that?

**Comment by PauMAVA** [comment]
It will be included in the next release, so yes, you will have to update the plugin.

For now, here you have  the last experimental build in which you can try this new locale:

[UhcPlugin-1.2.13-SNAPSHOT.jar.zip](https://github.com/PauMAVA/UhcPlugin/files/4229710/UhcPlugin-1.2.13-SNAPSHOT.jar.zip)
