### ISSUE TITLE
Super and Hyper golden apples.

### ISSUE THREAD

**Issue by PauMAVA** [PauMAVA/UhcPlugin#20]
Add Super Golden Apples (SGA) and Hyper Golden Apples (HGA). SGA fills 4 hearts and HGA adds 2 heart containers. (Limited to 15 per player).

**Comment by vichocruz** [comment]
Algo que me olvidé mencionar, pero que como tu también ves UHC España me imagino que sabías, es que el crafteo de la SGA es una golden apple rodeada de 8 de oro, y la HGA es una SGA rodeada de 8 de oro.

**Comment by PauMAVA** [comment]
@vichocruz
El funcionamiento es el esperado?
Recipe para SGA:
![imagen](https://user-images.githubusercontent.com/36012050/80916998-810f6980-8d5c-11ea-873a-4d192fcf2e5c.png)

Recipe para HGA:
![imagen](https://user-images.githubusercontent.com/36012050/80917019-9edcce80-8d5c-11ea-82b9-4d3a24db2423.png)

Comportamiento para SGA y HGA:
![ezgif-2-f38dcec72c14](https://user-images.githubusercontent.com/36012050/80921332-09e6cf00-8d76-11ea-880d-26f8d19792f1.gif)

**Comment by vichocruz** [comment]
Se alcanza a ver la cantidad de corazones que sube la SGA y está perfecto. De la HGA se corta justo al final de la regeneración, pero si regenera 2 corazones está perfecto también. Pero la cantidad de contenedores que entrega la HGA está errada, debería dar solo 2 contenedores extra, no 20.

**Comment by PauMAVA** [comment]
Pondré una opción en la config para poder especificar los contenedores.

Gracias :)

**Comment by vichocruz** [comment]
A ti! Muchas gracias por implementar todas estas cosas y tomar en cuenta mis propuestas ;)

**Comment by PauMAVA** [comment]
Default options:
```
# Hyper golden apple settings
hga:
  containers: 2 # 1 container = 2 hp (1 heart)
```

**Comment by PauMAVA** [comment]
Añadido.

En la pestaña projects del repo puedes ir viendo que features he implementado hasta ahora.
