### ISSUE TITLE
How to install and upload the plugin to my server

### ISSUE THREAD

**Issue by Drox27** [PauMAVA/UhcPlugin#35]
I also have another question. I upload it to my server on 1.15.2 and it is not working. I introduced UHCplugin-master file into the plugin file but it doesn´t works. Im doing something wrong?

**Comment by PauMAVA** [comment]
Can you please post the error message on the console?

**Comment by Drox27** [comment]
Sorry, I'm spanish and my English is not verey well. I mean, there is no error message, when I download the files, add them to the plugin file in filezilla and there enter to the server the plugin dont works. It is like it doesn't exists. When I do /plugin list it dont showsme the plugin.

**Comment by PauMAVA** [comment]
Podemos hablar en español si quieres. xD

¿Que servicio de hosting usas?

**Comment by Drox27** [comment]
Ok xD uso shockbyte

**Comment by PauMAVA** [comment]
Debes ir al [MultiCraft de shockbyte](https://mc.shockbyte.com/index.php?r=site/login) e iniciar sesión con las credenciales  que te hayan facilitado. Allí vas a la pestaña de servers y seleccionas tu server. Lo reinicias con el botón restart y te vas rapídamente a la consola (menú izquierdo). 

Si el plugin no aparece en /plugins entonces seguro que va a salir un error en la consola.

Y una pregunta. ¿Desde dónde estás descargando el plugin?

Ya me dices que tal 😄

**Comment by Drox27** [comment]
Estoy instalando el plugin desde add file y luego desde upload file. NO se si lo estar haciendo bien xD. Habe ya he hecho lo que me has dicho y no me sale ningun error, simplemente me dice los otros 2 plugins que tengo instalados, del otro nada. Gracias por la ayuda

**Comment by PauMAVA** [comment]
Pueba con este .jar.

[UhcPlugin-OfficialRelase-1.1.jar](https://github.com/PauMAVA/UhcPlugin/releases/download/v1.1/UhcPlugin-OfficialRelease-1.1.jar)

**Comment by Drox27** [comment]
ok, perfe si hay algun problema te aviso, almenos ya funciona :)

**Comment by Drox27** [comment]
porcierto, hay alguna forma de contactarte¿? discord, twitter o algo. Es que tengo varias dudas y me es mucho mas comodo.

**Comment by PauMAVA** [comment]
Me puedes contactar en discord: PauMAVA#3459

Me alegro que te funcione! 😄
