### ISSUE TITLE
Soy Lau (?)

### ISSUE THREAD

**Issue by andyvonde** [PauMAVA/UhcPlugin#38]
Pau, disculpa que te abra un issue, pero perdí tu contacto en discord porque me banearon la otra cuenta.
Te dejo el nuevo xD, avísame que cierro este issue de mierda. Lauu#8445

**Comment by PauMAVA** [comment]
Me sale que el user no se encuentra.

**Comment by andyvonde** [comment]
Łau#8445

No me notificó
