### ISSUE TITLE
Error al iniciar una partida.

### ISSUE THREAD

**Issue by andyvonde** [PauMAVA/UhcPlugin#4]
Probé alguna de las funciones en la 1.14.4
El comando /uhc start genera un búcle infinito (me pasó la 2da vez que lo utilice).
El comando de configuración para que el borde no se cierre, solo acepta "true" como parámetro. Debería aceptar false igualmente.

(Creo) que algunas excepciones no están controladas. Loguea muchas cosas en consola.

**Comment by andyvonde** [comment]
Confirmo, el empezar partida entra en búcle.

**Comment by PauMAVA** [comment]
Buenas!

Muchas gracias por hacerme llegar estos bugs. En un rato me lo miro y trato de solucionarlos.

**Comment by andyvonde** [comment]
No sé si tendrás discord, para hablar mejor xD (Sorry por ponerlo en un issue)

**Comment by PauMAVA** [comment]
Ya está bien que lo pongas en issues, yo lo clasificaría como tal.

**Comment by andyvonde** [comment]
Me refiero a pedir tu discord por issue, ya te envié solicitud.

**Comment by PauMAVA** [comment]
Se ha quitado el logging innecesario en el commit 9c9eaeaeabbd2fef7492b6b2bfa0527ba3bd0e7f

**Comment by PauMAVA** [comment]
Se ha dejado de dar soporte a la 1.14.4 con el prelanzamiento de Optifine 1.15.2.
